config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :registered_applications

  get 'about' => 'welcome#about'

  root 'welcome#index'
  
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
    belongs_to :registered_application
end

app/models/registered_application.rb
class RegisteredApplication < ApplicationRecord
  belongs_to :user
  has_many :events
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  has_many :registered_applications
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/registered_applications_controller.rb
class RegisteredApplicationsController < ApplicationController

  def index
    @registered_applications = RegisteredApplication.all
  end
  
  def show
    @user = current_user
    @registered_application = RegisteredApplication.find(params[:id])
    @events = @registered_application.events.group_by(&:name)
  end
  
  def new
    @user = current_user
    @registered_application = RegisteredApplication.new
  end
  
  def create
    @user = current_user
    @registered_application = @user.registered_applications.new(registered_application_params)

    if @registered_application.save
      flash[:notice]="The application was saved"
      redirect_to @registered_application
    else
      flash[:alert]="Application not saved"
      render :new
    end
  end

  def edit
    @user = current_user
    @registered_application = RegisteredApplication.find(params[:id])
  end
    
  def update
    @user = current_user
    @registered_application = RegisteredApplication.find(params[:id])
    @registered_application.name = params[:registered_application][:name]
    @registered_application.url = params[:registered_application][:url]
 
    if @registered_application.save
      flash[:notice] = "Application was updated successfully."
      redirect_to @registered_application
    else
      flash.now[:alert] = "There was an error saving the application. Please try again."
      render :edit
    end
  end

  def destroy
    @user = current_user
    @registered_application = @user.registered_applications.find(params[:id])

    if @registered_application.destroy
      flash[:notice]="Application has been destroyed"
      redirect_to registered_applications_path
    else
      flash[:alert]="Error"
    end
    respond_to do |format|
      format.html
      format.js
    end
  end

private
  def registered_application_params
    params.require(:registered_application).permit(:name, :url)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/registered_applications_helper.rb
module RegisteredApplicationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Analytics</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <ul class="nav nav-tabs">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "New", new_registered_application_path %></li>
        <li><%= link_to "Registered Applications", registered_applications_path %></li>
      </ul>
      <div class="pull-right user-info">
         <% if user_signed_in? %>
           Signed in as: <strong><%= current_user.email %></strong> |
           <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
         <% else %>
           <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> -
           <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
         <% end %>
      </div>
    </div>
    <div class="container">
      <%= yield %>
    </div>
  </body>
  
</html>

app/views/registered_applications/_form.html.erb
 <h4>Add an Application</h4>

 <%= form_for [user, registered_application] do |f| %>
   <div class="form-group">
     <%= f.label :name, class: 'sr-only' %>
     <%= f.text_field :name, class: 'form-control', placeholder: "Enter a new application" %>
     <%= f.text_field :url, class: 'form-control', placeholder: "Enter the url for the application" %>
   </div>
   <%= f.submit "Submit Item", class: 'btn btn-default pull-right' %>
 <% end %>

app/views/registered_applications/_registered_application.html.erb
<tbody>
  <%= content_tag :tr, class: "info", id: "registered_application-#{registered_application.id}" do %>
    <td><%= registered_application.name %></td>
    <td><%= link_to "", [current_user, registered_application], method: :delete, class: 'glyphicon glyphicon-ok', remote: true %></td>
  <% end %>
</tbody>

app/views/registered_applications/destroy.html.erb
 <% if @registered_application.destroyed? %>
   $('#registered_application-<%= @registered_application.id %>').fadeOut(1300);
 <% else %>
   $('.flash').prepend("<div class='alert alert-danger'><button type='button' class='close' data-dismiss='alert'>&times;</button><%= flash.now[:alert] %></div>");
 <% end %>

app/views/registered_applications/edit.html.erb
 <h1>Edit Application</h1>
 
 <div class="row">
   <div class="col-md-4">
     <p>Guidelines for Applications</p>
     <ul>
       <li>Nothing innappropriate.</li>
       <li>Puppy applications prefered.</li>
     </ul>
   </div>
   <div class="col-md-8">
     <%= form_for @registered_application do |f| %>
       <div class="form-group">
         <%= f.label :name %>
         <%= f.text_field :name, class: 'form-control', placeholder: "Enter application name" %>
       </div>
       <div class="form-group">
         <%= f.label :url %>
         <%= f.text_area :url, rows: 8, class: 'form-control', placeholder: "Enter URL for application" %>
       </div>
       <div class="form-group">
         <%= f.submit "Save", class: 'btn btn-success' %>
       </div>
     <% end %>
   </div>
 </div>

app/views/registered_applications/index.html.erb
 <h1>All Registered Applications</h1>
 
 <% @registered_applications.each do |registered_application| %>
   <div class="media">
     <div class="media-body">
       <h4 class="media-heading">
         <%= link_to registered_application.name, registered_application %>
       </h4>
     </div>
   </div>
 <% end %>

app/views/registered_applications/new.html.erb
 <h1>New Application</h1>
 
 <div class="row">
   <div class="col-md-4">
     <p>Guidelines for Applications</p>
     <ul>
       <li>Nothing innappropriate.</li>
       <li>Puppy applications prefered.</li>
     </ul>
   </div>
   <div class="col-md-8">
     <%= form_for @registered_application do |f| %>
       <div class="form-group">
         <%= f.label :name %>
         <%= f.text_field :name, class: 'form-control', placeholder: "Enter application name" %>
       </div>
       <div class="form-group">
         <%= f.label :url %>
         <%= f.text_area :url, rows: 8, class: 'form-control', placeholder: "Enter URL for application" %>
       </div>
       <div class="form-group">
         <%= f.submit "Save", class: 'btn btn-success' %>
       </div>
     <% end %>
   </div>
 </div>

app/views/registered_applications/show.html.erb
 <h1><%= @registered_application.name %></h1>
 
 <div class="row">
   <div class="col-md-8">
     <p><%= @registered_application.url %></p>
   </div>
   <div class="col-md-4">
     <%= link_to "Edit", edit_registered_application_path(@registered_application), class: 'btn btn-success' %>
     <%= link_to "Delete Application", @registered_application, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this application?'} %>
   </div>
 </div>
 
 <h3>Events</h3>
  <% @events.each do |event, count| %>
    <%= "#{event}: #{count.length}" %><br />
  <% end %>

app/views/users/show.html.erb
 <div class="row">
   <div class="col-md-8">
     <div class="media">
       <div class="media-body">
         <h2 class="media-heading">Welcome <%= @user.email %>!</h2>
         <small>
         </small>
       </div>
     </div>
   </div>
 </div>
 
 <h3>Applications</h3>

<div class="row">
  <div class="col-md-8">
     <% @user.registered_applications.each do |user.registered_application| %>
       <div class="media">
         <div class="media-body">
           <h4 class="media-heading">
             <%= link_to registered_application.name, user.registered_application %>
           </h4>
           <small>
             <%= user.registered_application.url %>
           </small>
         </div>
       </div>
     <% end %>
   </div>

app/views/welcome/about.html.erb
<h1>About Bloccit</h1>
<p>Created by: Me</p>

app/views/welcome/index.html.erb
 <br>
 <div class="jumbotron">
   <h1>Analytics</h1>
   <p>Analytics is a resource for finding out about your website!</p>
   <p>
     <%= link_to "Sign In", new_user_session_path %> or
     <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary' %> today!
   </p>
 </div>

 <div class="row">
   <div class="col-md-4">
     <h2>This Application will tell you how many people have visited your website.</h2>
     <p>In case you don't want to just use a hit counter.</p>
   </div>
 </div>